name: CI/CD

permissions: write-all

on:
  push:
    branches:
      - "main"

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      SHA: ${{ steps.get_sha.outputs.SHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get SHA
        id: get_sha
        run: echo "SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: preparation

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          SHA: ${{ needs.preparation.outputs.SHA }}
        run: docker build -t ghcr.io/rashio-bangkit-capstone/prediction-service:$SHA .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        env:
          SHA: ${{ needs.preparation.outputs.SHA }}
        run: docker push ghcr.io/rashio-bangkit-capstone/prediction-service:$SHA

  deploy:
    runs-on: ubuntu-latest
    needs:
      - preparation
      - build

    steps:
      - name: Update Docker Compose via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          SHA: ${{ needs.preparation.outputs.SHA }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: SHA
          timeout: 1h
          script: |
            cd ~ \
            && sudo ls -l \
            && sudo sed -i "s/image: ghcr.io\/rashio-bangkit-capstone\/prediction-service:.*/image: ghcr.io\/rashio-bangkit-capstone\/prediction-service:$SHA/g" docker-compose.yml \
            && sudo docker compose up prediction-service -d
